/* Generated by scripts/gen-compass-illustrations.mjs — do not edit by hand */
import type { ComponentType, SVGProps } from 'react';
import AiCopilotIntroIllustration from '@/illustrations/ai-copilot-intro';
import AlertIllustration from '@/illustrations/alert';
import AlertOnSidebarBgIllustration from '@/illustrations/alert-on-sidebar-bg';
import ArchivedChannelIllustration from '@/illustrations/archived-channel';
import AutoTranslationIllustration from '@/illustrations/auto-translation';
import BannersIllustration from '@/illustrations/banners';
import BillingHistoryIllustration from '@/illustrations/billing-history';
import BlankPlaybookIllustration from '@/illustrations/blank-playbook';
import BotAccountsIllustration from '@/illustrations/bot-accounts';
import BrowserOrDesktopIllustration from '@/illustrations/browser-or-desktop';
import BugBashIllustration from '@/illustrations/bug-bash';
import CallsIllustration from '@/illustrations/calls';
import CollaborateIllustration from '@/illustrations/collaborate';
import ComplianceExportsIllustration from '@/illustrations/compliance-exports';
import CopilotBotIllustration from '@/illustrations/copilot-bot';
import CustomBrandingIllustration from '@/illustrations/custom-branding';
import CustomTermsIllustration from '@/illustrations/custom-terms';
import CustomerOnboardingIllustration from '@/illustrations/customer-onboarding';
import DataRetentionIllustration from '@/illustrations/data-retention';
import DraftsEmptyIllustration from '@/illustrations/drafts-empty';
import EmployeeOnboardingIllustration from '@/illustrations/employee-onboarding';
import FeatureLifecycleIllustration from '@/illustrations/feature-lifecycle';
import FileSearchEmptyIllustration from '@/illustrations/file-search-empty';
import GlobeIllustration from '@/illustrations/globe';
import GroupIllustration from '@/illustrations/group';
import GroupsIllustration from '@/illustrations/groups';
import IncidentResolutionIllustration from '@/illustrations/incident-resolution';
import IncomingWebhookIllustration from '@/illustrations/incoming-webhook';
import IntuneMamIllustration from '@/illustrations/intune-mam';
import LearnPlaybooksIllustration from '@/illustrations/learn-playbooks';
import LockedMessagesIllustration from '@/illustrations/locked-messages';
import MentionsEmptyIllustration from '@/illustrations/mentions-empty';
import MessageNotViewableIllustration from '@/illustrations/message-not-viewable';
import MessageSearchEmptyIllustration from '@/illustrations/message-search-empty';
import MfaIllustration from '@/illustrations/mfa';
import MfaCompleteIllustration from '@/illustrations/mfa-complete';
import MobileProtectionIllustration from '@/illustrations/mobile-protection';
import MobileSecurityIllustration from '@/illustrations/mobile-security';
import NewPasswordIllustration from '@/illustrations/new-password';
import NoUnreadsOnSidebarBgIllustration from '@/illustrations/no-unreads-on-sidebar-bg';
import OfficeIllustration from '@/illustrations/office';
import OutgoingWebhookIllustration from '@/illustrations/outgoing-webhook';
import PinnedEmptyIllustration from '@/illustrations/pinned-empty';
import PlaybooksEmptyIllustration from '@/illustrations/playbooks-empty';
import PrivateChannelIntroIllustration from '@/illustrations/private-channel-intro';
import ProductReleaseIllustration from '@/illustrations/product-release';
import PublicChannelIntroIllustration from '@/illustrations/public-channel-intro';
import RatingIllustration from '@/illustrations/rating';
import RatingDesktopIllustration from '@/illustrations/rating-desktop';
import ReadOnlyIllustration from '@/illustrations/read-only';
import ResetPasswordIllustration from '@/illustrations/reset-password';
import SavedEmptyIllustration from '@/illustrations/saved-empty';
import ScheduledEmptyIllustration from '@/illustrations/scheduled-empty';
import SearchIllustration from '@/illustrations/search';
import ServerIllustration from '@/illustrations/server';
import SetupSystemIllustration from '@/illustrations/setup-system';
import SiteErrorIllustration from '@/illustrations/site-error';
import SlashCommandsIllustration from '@/illustrations/slash-commands';
import SuccessIllustration from '@/illustrations/success';
import SystemAdminsIllustration from '@/illustrations/system-admins';
import ThreadsEmptyIllustration from '@/illustrations/threads-empty';
import TimerIllustration from '@/illustrations/timer';
import TlsCertificateIllustration from '@/illustrations/tls-certificate';
import ToolsIllustration from '@/illustrations/tools';
import TownSquareChannelIntroIllustration from '@/illustrations/town-square-channel-intro';
import UploadLicenseIllustration from '@/illustrations/upload-license';
import VerifyEmailIllustration from '@/illustrations/verify-email';

export type CompassIllustration = ComponentType<SVGProps<SVGSVGElement>>;

export const STORYBOOK_ILLUSTRATIONS = {
  'ai-copilot-intro': AiCopilotIntroIllustration,
  'alert': AlertIllustration,
  'alert-on-sidebar-bg': AlertOnSidebarBgIllustration,
  'archived-channel': ArchivedChannelIllustration,
  'auto-translation': AutoTranslationIllustration,
  'banners': BannersIllustration,
  'billing-history': BillingHistoryIllustration,
  'blank-playbook': BlankPlaybookIllustration,
  'bot-accounts': BotAccountsIllustration,
  'browser-or-desktop': BrowserOrDesktopIllustration,
  'bug-bash': BugBashIllustration,
  'calls': CallsIllustration,
  'collaborate': CollaborateIllustration,
  'compliance-exports': ComplianceExportsIllustration,
  'copilot-bot': CopilotBotIllustration,
  'custom-branding': CustomBrandingIllustration,
  'custom-terms': CustomTermsIllustration,
  'customer-onboarding': CustomerOnboardingIllustration,
  'data-retention': DataRetentionIllustration,
  'drafts-empty': DraftsEmptyIllustration,
  'employee-onboarding': EmployeeOnboardingIllustration,
  'feature-lifecycle': FeatureLifecycleIllustration,
  'file-search-empty': FileSearchEmptyIllustration,
  'globe': GlobeIllustration,
  'group': GroupIllustration,
  'groups': GroupsIllustration,
  'incident-resolution': IncidentResolutionIllustration,
  'incoming-webhook': IncomingWebhookIllustration,
  'intune-mam': IntuneMamIllustration,
  'learn-playbooks': LearnPlaybooksIllustration,
  'locked-messages': LockedMessagesIllustration,
  'mentions-empty': MentionsEmptyIllustration,
  'message-not-viewable': MessageNotViewableIllustration,
  'message-search-empty': MessageSearchEmptyIllustration,
  'mfa': MfaIllustration,
  'mfa-complete': MfaCompleteIllustration,
  'mobile-protection': MobileProtectionIllustration,
  'mobile-security': MobileSecurityIllustration,
  'new-password': NewPasswordIllustration,
  'no-unreads-on-sidebar-bg': NoUnreadsOnSidebarBgIllustration,
  'office': OfficeIllustration,
  'outgoing-webhook': OutgoingWebhookIllustration,
  'pinned-empty': PinnedEmptyIllustration,
  'playbooks-empty': PlaybooksEmptyIllustration,
  'private-channel-intro': PrivateChannelIntroIllustration,
  'product-release': ProductReleaseIllustration,
  'public-channel-intro': PublicChannelIntroIllustration,
  'rating': RatingIllustration,
  'rating-desktop': RatingDesktopIllustration,
  'read-only': ReadOnlyIllustration,
  'reset-password': ResetPasswordIllustration,
  'saved-empty': SavedEmptyIllustration,
  'scheduled-empty': ScheduledEmptyIllustration,
  'search': SearchIllustration,
  'server': ServerIllustration,
  'setup-system': SetupSystemIllustration,
  'site-error': SiteErrorIllustration,
  'slash-commands': SlashCommandsIllustration,
  'success': SuccessIllustration,
  'system-admins': SystemAdminsIllustration,
  'threads-empty': ThreadsEmptyIllustration,
  'timer': TimerIllustration,
  'tls-certificate': TlsCertificateIllustration,
  'tools': ToolsIllustration,
  'town-square-channel-intro': TownSquareChannelIntroIllustration,
  'upload-license': UploadLicenseIllustration,
  'verify-email': VerifyEmailIllustration,
} as const satisfies Record<string, CompassIllustration>;

export type StorybookIllustrationName = keyof typeof STORYBOOK_ILLUSTRATIONS;

export const STORYBOOK_ILLUSTRATION_NAMES = Object.keys(
  STORYBOOK_ILLUSTRATIONS,
) as StorybookIllustrationName[];
